version: "3.9"
networks:
  nitro-web_default:
    external: true

volumes:
  db_data:
  redis_data:

services:
  redis:
    extends:
      file: ~/repos/nitro-web/docker-compose.yml
      service: redis
    networks:
      - nitro-web_default

  db:
    extends:
      file: ~/repos/nitro-web/docker-compose.yml
      service: db
    networks:
      - nitro-web_default

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    networks:
      - nitro-web_default

  pantab_server:
    build: pantab_server
    command: python server.py
    volumes:
      - ./pantab_server:/pantab_server
      - ./datasets:/datasets
    ports:
      - 3333:3333
