version: "3.9"
services:
  redis:
    image: bitnami/redis:6.2.6
    environment:
      ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - 6380:6379
    mem_limit: 100m

  db:
    image: amd64/mysql:8.0.29
    ports:
      - 3456:3306
    environment:
      MYSQL_DATABASE: oxygen_dev
      MYSQL_ROOT_PASSWORD: oxygen
    mem_limit: 2g

  pantab_server:
    build: pantab_server
    command: python server.py
    volumes:
      - ./pantab_server:/pantab_server
      - ./datasets:/datasets
    ports:
      - 3333:3333
