# Generated by Django 4.0.4 on 2022-06-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oracle', '0002_dataset_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasettable',
            name='connector',
            field=models.CharField(default='mysql', max_length=30),
        ),
    ]
