# Generated by Django 4.0.4 on 2022-06-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oracle', '0003_datasettable_connector'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasettable',
            name='x',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datasettable',
            name='y',
            field=models.SmallIntegerField(default=0),
        ),
    ]
