fragment WidgetParts on Widget {
  id
  title
  type
  buildInfo
  renderData {
    ... on PivotTableRenderData {
      html
    }
    ... on ChartRenderData {
      html
    }
  }

  layout {
    i
    w
    h
    x
    y
  }
}
