mutation createDatasetTable($datasetId: ID!, $name: String!, $query: String!) {
  createDatasetTable(datasetId: $datasetId, name: $name, query: $query) {
    dataset {
      ...DatasetParts
    }
  }
}
