query dashboard($id: ID!) {
  dashboard(id: $id) {
    ...DashboardParts

    dataset {
      ...DatasetParts

      tables {
        ...DatasetTableParts
      }
    }

    widgets {
      ...WidgetParts
    }
  }
}
