# Generated by Django 4.0.4 on 2022-05-26 22:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('o2', '0010_dataset_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='grid_rows',
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('type', models.CharField(max_length=20)),
                ('build_info', models.JSONField()),
                ('meta', models.JSONField()),
                ('dataset', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='o2.dataset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DashboardRows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='o2.dashboard')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='o2.widget')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
