# Generated by Django 4.0.4 on 2022-05-27 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('o2', '0011_rename_title_dashboard_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DashboardRows',
            new_name='DashboardRow',
        ),
    ]
