# Generated by Django 4.0.4 on 2022-05-30 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('o2', '0019_rename_count_dataset_totalrecords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='dashboard_row',
        ),
        migrations.AddField(
            model_name='widget',
            name='dashboard',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='o2.dashboard'),
        ),
    ]
