# Generated by Django 4.0.4 on 2022-05-31 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o2', '0025_alter_dataset_build_duration_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='grid_rows',
            field=models.JSONField(null=True),
        ),
    ]
