# Generated by Django 4.0.4 on 2022-06-02 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('o2', '0027_alter_datasettable_dataset_alter_datasettable_fields_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='grid_rows',
            new_name='layout',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='previous_version',
        ),
        migrations.AlterField(
            model_name='widget',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='o2.dashboard'),
        ),
    ]
