# Generated by Django 4.0.4 on 2022-06-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o2', '0028_rename_grid_rows_dashboard_layout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='grid_row_index',
        ),
        migrations.AlterField(
            model_name='widget',
            name='build_info',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='type',
            field=models.CharField(choices=[('Pivot Table', 'Pivot Table'), ('Line Chart', 'Line Chart'), ('Vertical Bar Chart', 'Vertical Bar Chart')], max_length=20),
        ),
    ]
