# Generated by Django 4.0.4 on 2022-06-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o2', '0030_alter_dashboard_layout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='layout',
        ),
        migrations.AddField(
            model_name='widget',
            name='layout',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='widget',
            name='build_info',
            field=models.JSONField(default=dict),
        ),
    ]
