# Generated by Django 4.0.4 on 2022-06-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o2', '0031_remove_dashboard_layout_widget_layout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='layout',
            field=models.JSONField(),
        ),
    ]
