# Generated by Django 4.0.4 on 2022-06-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o2', '0033_alter_dashboard_dataset_alter_widget_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='layout',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='title',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='layout',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
