# Generated by Django 4.0.4 on 2022-06-04 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('o2', '0034_remove_widget_layout_remove_widget_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasettable',
            name='fields',
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='layout',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='DatasetTableColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Text', 'Text'), ('Integer', 'Integer'), ('Float', 'Float'), ('DateTime', 'Datetime')], max_length=20)),
                ('join_type', models.CharField(choices=[('INNER JOIN', 'Inner Join'), ('LEFT JOIN', 'Left Join')], max_length=20)),
                ('foreign_key_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='o2.datasettablecolumn')),
                ('foreign_key_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreign_keys', to='o2.datasettable')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='o2.datasettable')),
            ],
        ),
    ]
