# Generated by Django 4.0.4 on 2022-06-04 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('o2', '0035_remove_datasettable_fields_alter_dashboard_layout_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasettablecolumn',
            old_name='foreign_key_field',
            new_name='foreign_key_column',
        ),
        migrations.AlterField(
            model_name='datasettablecolumn',
            name='foreign_key_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='o2.datasettable'),
        ),
    ]
