# Generated by Django 4.0.4 on 2022-06-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o2', '0037_alter_datasettablecolumn_foreign_key_column_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasettablecolumn',
            name='foreign_key_column',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datasettablecolumn',
            name='foreign_key_table',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
