# Generated by Django 4.0.4 on 2022-06-07 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('o2', '0040_alter_dashboard_dataset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasettablecolumn',
            name='foreign_key',
        ),
        migrations.RemoveField(
            model_name='datasettablecolumn',
            name='join_type',
        ),
    ]
