# Generated by Django 4.0.4 on 2022-06-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o2', '0041_remove_datasettablecolumn_foreign_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasettable',
            name='table_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
